We are also allowed to write lib interface files at each level.
  $ dune build
  defined in lib interface file
  hello from baz

  $ find _build -iname "*.cmi"
  _build/default/exe/.test.eobjs/byte/Test__Dune__exe.cmi
  _build/default/lib/.foolib.objs/byte/Foolib__Bar__.cmi
  _build/default/lib/.foolib.objs/byte/Foolib__.cmi
  _build/default/lib/.foolib.objs/byte/Foolib.cmi
  _build/default/lib/.foolib.objs/byte/Foolib__Private.cmi
  _build/default/lib/.foolib.objs/byte/Foolib__Bar.cmi
  _build/default/lib/.foolib.objs/byte/Foolib__Bar__Baz.cmi

  $ find _build -iname "*.ml-gen" | while read file; do echo "contents of $file"; cat $file; echo "--------"; done;
  contents of _build/default/lib/Foolib__Bar__.ml-gen
  (* generated by dune *)
  
  (** @canonical Foolib.Baz *)
  module Baz = Foolib__Bar__Baz
  
  module Foolib__Bar__ = struct end
  [@@deprecated "this module is shadowed"]
  --------
  contents of _build/default/lib/Foolib__.ml-gen
  (* generated by dune *)
  
  (** @canonical Foolib.Bar *)
  module Bar = Foolib__Bar
  
  (** @canonical Foolib.Private *)
  module Private = Foolib__Private
  
  module Foolib__ = struct end
  [@@deprecated "this module is shadowed"]
  --------
